### ISSUE TITLE
Nice！

### ISSUE THREAD

**Issue by ZYK23** [hustvl/SparseTrack#11]
SparseTrack is a simple and efficient tracker that makes perfect use of 2D image pseudo-depth information to achieve efficient performance, which is great to work with!

**Comment by Xavier-Lin** [comment]
@ZYK23 Thank you for your interest and support in SparseTrack.

**Comment by Xavier-Lin** [comment]
@ZYK23 
If you don't have any further questions, I will consider closing this issue. Thank you for your interest in SparseTrack.
