### ISSUE TITLE
Weight file for "yolox_x_mot20_ablation"

### ISSUE THREAD

**Issue by kamkyu94** [hustvl/SparseTrack#12]
Hello.

Thank you for sharing the great work about multi-object tracking, and I hope this message finds you well. 

I wanted to inquire about the availability of the weight file for "yolox_x_mot20_ablation." 
If I click the link, access to the google drive is denied, and it is not able to download the weight file.

Can you let me know when I can expect to have access to the aforementioned weight file? 
Your assistance is greatly appreciated.

Thank you very much for your help.

**Comment by Xavier-Lin** [comment]
@kamkyu94  I have enabled file sharing permissions. You can try downloading the weight file.

**Comment by kamkyu94** [comment]
Thank you so much!
