### ISSUE TITLE
dancetrack model weight

### ISSUE THREAD

**Issue by l-sf** [hustvl/SparseTrack#16]
作者您好，dancetrack 的模型权重 Google drive 无法访问！

**Comment by Xavier-Lin** [comment]
稍等，我改一下链接

**Comment by l-sf** [comment]
感谢您的回复！

不好意思再打扰一下，dancetrack的权重您提供的三个链接，第一个仍然没有权限，第二百度云里面是mot20_ablation的，第三个是个文件夹，里面有个bytetrack_model.pth，请问是下载这个吗？

![image](https://github.com/hustvl/SparseTrack/assets/78126612/1c6fac80-7897-4831-af00-73923ee7d286)

另外再问一下，这个dancetrack的权重是您重新训练的还是使用的OC-SORT提供的权重？

**Comment by Xavier-Lin** [comment]
下载第三个链接的内容即可（bytetrack_model.pth），权重均使用dancetrack项目提供的权重，没有重新训练

**Comment by l-sf** [comment]
好的，谢谢！
