### ISSUE TITLE
Evalutation results on MOT20 test set

### ISSUE THREAD

**Issue by caijier1** [hustvl/SparseTrack#22]
On the official MOT20 test set, why do I only get 76.2 MOTA and 77.0 IDF1 by running this code？In addition to GMC, is there anything else that needs to be paid attention to and adjusted in the code when running the MOT20 test set?

**Comment by Xavier-Lin** [comment]
For running at MOT20 test set, you can run the code with the 896 x 1600 resolution over MOT20-04 and MOT20-07, and the  736 x 1920 resolution over MOT20-06 and MOT20-08. Additionally, the GMC is not used in testing in MOT20 dataset.

**Comment by caijier1** [comment]
Niubi

**Comment by luke110** [comment]
> On the official MOT20 test set, why do I only get 76.2 MOTA and 77.0 IDF1 by running this code？In addition to GMC, is there anything else that needs to be paid attention to and adjusted in the code when running the MOT20 test set?

你好，请问你是如何实验得到MOTA IDF1评分的呢。我在评估mot17时遇到了
/HOME/scw6492/run/luke/yolov8/TrackEval
/HOME/scw6492/run/luke/yolov8/TrackEval
/HOME/scw6492/run/luke/yolov8/TrackEval

Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 1                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /HOME/scw6492/run/luke/yolov8/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          
/HOME/scw6492/run/luke/yolov8/TrackEval

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /HOME/scw6492/run/luke/yolov8/MOT17
TRACKERS_FOLDER      : /HOME/scw6492/run/luke/yolov8/run/train/test2/yolov8_mot17
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['MPNTrack']                  
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : MOT17                         
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : /HOME/scw6492/run/luke/yolov8/TrackEval/data/gt/mot_challenge/seqmaps/MOT17-train.txt
SEQ_INFO             : None                          
GT_LOC_FORMAT        : /HOME/scw6492/run/luke/yolov8/MOT17/train/{seq}/gt/gt_val_half.txt
SKIP_SPLIT_FOL       : False                         
Traceback (most recent call last):
  File "/HOME/scw6492/run/luke/yolov8/TrackEval/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 103, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 188, in _get_seq_info
    raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file))
trackeval.utils.TrackEvalException: ini file does not exist: MOT17-02-SDP/seqinfo.ini这样的报错。




请问你有什么建议吗

**Comment by caijier1** [comment]
我是直接跑的作者提供的track.py，然后把结果上传到MOT Challenge官网测的

**Comment by caijier1** [comment]
我是直接跑的作者提供的track.py，然后提交MOT Challenge官网上测的
&nbsp;


nizhixiang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月16日(星期二) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [hustvl/SparseTrack] Evalutation results on MOT20 test set (Issue #22)





  
On the official MOT20 test set, why do I only get 76.2 MOTA and 77.0 IDF1 by running this code？In addition to GMC, is there anything else that needs to be paid attention to and adjusted in the code when running the MOT20 test set?
  
你好，请问你是如何实验得到MOTA IDF1评分的呢。我在评估mot17时遇到了
 /HOME/scw6492/run/luke/yolov8/TrackEval
 /HOME/scw6492/run/luke/yolov8/TrackEval
 /HOME/scw6492/run/luke/yolov8/TrackEval
 
Eval Config:
 USE_PARALLEL         : False
 NUM_PARALLEL_CORES   : 1
 BREAK_ON_ERROR       : True
 RETURN_ON_ERROR      : False
 LOG_ON_ERROR         : /HOME/scw6492/run/luke/yolov8/TrackEval/error_log.txt
 PRINT_RESULTS        : True
 PRINT_ONLY_COMBINED  : False
 PRINT_CONFIG         : True
 TIME_PROGRESS        : True
 DISPLAY_LESS_PROGRESS : False
 OUTPUT_SUMMARY       : True
 OUTPUT_EMPTY_CLASSES : True
 OUTPUT_DETAILED      : True
 PLOT_CURVES          : True
 /HOME/scw6492/run/luke/yolov8/TrackEval
 
MotChallenge2DBox Config:
 PRINT_CONFIG         : True
 GT_FOLDER            : /HOME/scw6492/run/luke/yolov8/MOT17
 TRACKERS_FOLDER      : /HOME/scw6492/run/luke/yolov8/run/train/test2/yolov8_mot17
 OUTPUT_FOLDER        : None
 TRACKERS_TO_EVAL     : ['MPNTrack']
 CLASSES_TO_EVAL      : ['pedestrian']
 BENCHMARK            : MOT17
 SPLIT_TO_EVAL        : train
 INPUT_AS_ZIP         : False
 DO_PREPROC           : True
 TRACKER_SUB_FOLDER   : data
 OUTPUT_SUB_FOLDER    :
 TRACKER_DISPLAY_NAMES : None
 SEQMAP_FOLDER        : None
 SEQMAP_FILE          : /HOME/scw6492/run/luke/yolov8/TrackEval/data/gt/mot_challenge/seqmaps/MOT17-train.txt
 SEQ_INFO             : None
 GT_LOC_FORMAT        : /HOME/scw6492/run/luke/yolov8/MOT17/train/{seq}/gt/gt_val_half.txt
 SKIP_SPLIT_FOL       : False
 Traceback (most recent call last):
 File "/HOME/scw6492/run/luke/yolov8/TrackEval/scripts/run_mot_challenge.py", line 84, in 
 dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
 File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 103, in init
 self.seq_list, self.seq_lengths = self._get_seq_info()
 File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 188, in _get_seq_info
 raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file))
 trackeval.utils.TrackEvalException: ini file does not exist: MOT17-02-SDP/seqinfo.ini这样的报错。
 
请问你有什么建议吗

**Comment by luke110** [comment]
> 我是直接跑的作者提供的track.py，然后提交MOT Challenge官网上测的 &nbsp; nizhixiang ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年1月16日(星期二) 下午3:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [hustvl/SparseTrack] Evalutation results on MOT20 test set (Issue #22) On the official MOT20 test set, why do I only get 76.2 MOTA and 77.0 IDF1 by running this code？In addition to GMC, is there anything else that needs to be paid attention to and adjusted in the code when running the MOT20 test set? 你好，请问你是如何实验得到MOTA IDF1评分的呢。我在评估mot17时遇到了 /HOME/scw6492/run/luke/yolov8/TrackEval /HOME/scw6492/run/luke/yolov8/TrackEval /HOME/scw6492/run/luke/yolov8/TrackEval Eval Config: USE_PARALLEL : False NUM_PARALLEL_CORES : 1 BREAK_ON_ERROR : True RETURN_ON_ERROR : False LOG_ON_ERROR : /HOME/scw6492/run/luke/yolov8/TrackEval/error_log.txt PRINT_RESULTS : True PRINT_ONLY_COMBINED : False PRINT_CONFIG : True TIME_PROGRESS : True DISPLAY_LESS_PROGRESS : False OUTPUT_SUMMARY : True OUTPUT_EMPTY_CLASSES : True OUTPUT_DETAILED : True PLOT_CURVES : True /HOME/scw6492/run/luke/yolov8/TrackEval MotChallenge2DBox Config: PRINT_CONFIG : True GT_FOLDER : /HOME/scw6492/run/luke/yolov8/MOT17 TRACKERS_FOLDER : /HOME/scw6492/run/luke/yolov8/run/train/test2/yolov8_mot17 OUTPUT_FOLDER : None TRACKERS_TO_EVAL : ['MPNTrack'] CLASSES_TO_EVAL : ['pedestrian'] BENCHMARK : MOT17 SPLIT_TO_EVAL : train INPUT_AS_ZIP : False DO_PREPROC : True TRACKER_SUB_FOLDER : data OUTPUT_SUB_FOLDER : TRACKER_DISPLAY_NAMES : None SEQMAP_FOLDER : None SEQMAP_FILE : /HOME/scw6492/run/luke/yolov8/TrackEval/data/gt/mot_challenge/seqmaps/MOT17-train.txt SEQ_INFO : None GT_LOC_FORMAT : /HOME/scw6492/run/luke/yolov8/MOT17/train/{seq}/gt/gt_val_half.txt SKIP_SPLIT_FOL : False Traceback (most recent call last): File "/HOME/scw6492/run/luke/yolov8/TrackEval/scripts/run_mot_challenge.py", line 84, in dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)] File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 103, in init self.seq_list, self.seq_lengths = self._get_seq_info() File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 188, in _get_seq_info raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file)) trackeval.utils.TrackEvalException: ini file does not exist: MOT17-02-SDP/seqinfo.ini这样的报错。 请问你有什么建议吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你是用自己跑出来的pth文件进行追踪的吗，我自己跑的保存不到model_0146239.pth，只能保存到model_0131615.pth。这个你能跑出model_0146239.pth吗。我是用的v8版本。你是怎么检查跑出的模型最优的是哪一个呢。

**Comment by caijier1** [comment]
> > 我是直接跑的作者提供的track.py，然后提交MOT Challenge官网上测的   nizhixiang _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年1月16日(星期二) 下午3:30 收件人: _**@**_.**_>; 抄送: _**@**_._**>; "State _**@**_.**_>; 主题: Re: [hustvl/SparseTrack] Evalutation results on MOT20 test set (Issue #22) On the official MOT20 test set, why do I only get 76.2 MOTA and 77.0 IDF1 by running this code？In addition to GMC, is there anything else that needs to be paid attention to and adjusted in the code when running the MOT20 test set? 你好，请问你是如何实验得到MOTA IDF1评分的呢。我在评估mot17时遇到了 /HOME/scw6492/run/luke/yolov8/TrackEval /HOME/scw6492/run/luke/yolov8/TrackEval /HOME/scw6492/run/luke/yolov8/TrackEval Eval Config: USE_PARALLEL : False NUM_PARALLEL_CORES : 1 BREAK_ON_ERROR : True RETURN_ON_ERROR : False LOG_ON_ERROR : /HOME/scw6492/run/luke/yolov8/TrackEval/error_log.txt PRINT_RESULTS : True PRINT_ONLY_COMBINED : False PRINT_CONFIG : True TIME_PROGRESS : True DISPLAY_LESS_PROGRESS : False OUTPUT_SUMMARY : True OUTPUT_EMPTY_CLASSES : True OUTPUT_DETAILED : True PLOT_CURVES : True /HOME/scw6492/run/luke/yolov8/TrackEval MotChallenge2DBox Config: PRINT_CONFIG : True GT_FOLDER : /HOME/scw6492/run/luke/yolov8/MOT17 TRACKERS_FOLDER : /HOME/scw6492/run/luke/yolov8/run/train/test2/yolov8_mot17 OUTPUT_FOLDER : None TRACKERS_TO_EVAL : ['MPNTrack'] CLASSES_TO_EVAL : ['pedestrian'] BENCHMARK : MOT17 SPLIT_TO_EVAL : train INPUT_AS_ZIP : False DO_PREPROC : True TRACKER_SUB_FOLDER : data OUTPUT_SUB_FOLDER : TRACKER_DISPLAY_NAMES : None SEQMAP_FOLDER : None SEQMAP_FILE : /HOME/scw6492/run/luke/yolov8/TrackEval/data/gt/mot_challenge/seqmaps/MOT17-train.txt SEQ_INFO : None GT_LOC_FORMAT : /HOME/scw6492/run/luke/yolov8/MOT17/train/{seq}/gt/gt_val_half.txt SKIP_SPLIT_FOL : False Traceback (most recent call last): File "/HOME/scw6492/run/luke/yolov8/TrackEval/scripts/run_mot_challenge.py", line 84, in dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)] File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 103, in init self.seq_list, self.seq_lengths = self._get_seq_info() File "/HOME/scw6492/run/luke/yolov8/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 188, in _get_seq_info raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file)) trackeval.utils.TrackEvalException: ini file does not exist: MOT17-02-SDP/seqinfo.ini这样的报错。 请问你有什么建议吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 你是用自己跑出来的pth文件进行追踪的吗，我自己跑的保存不到model_0146239.pth，只能保存到model_0131615.pth。这个你能跑出model_0146239.pth吗。我是用的v8版本。你是怎么检查跑出的模型最优的是哪一个呢。

我用的作者放出来的那个yolox的权重，没用yolov8的

**Comment by SmallGGgg** [comment]
> Niubi

大佬你好，请问按照作者说的：“you can run the code with the 896 x 1600 resolution over MOT20-04 and MOT20-07, and the 736 x 1920 resolution over MOT20-06 and MOT20-08. ”，具体代码要怎么修改呀？
