### ISSUE TITLE
cannot import pbcvt 

### ISSUE THREAD

**Issue by MattLiutt** [hustvl/SparseTrack#27]
Hi, I encountered a problem when I was running the script, which I cannot import the modules? Thanks so much
![image](https://github.com/hustvl/SparseTrack/assets/155410644/82f57aa5-b0c6-4b4c-990c-313814193983)

**Comment by MattLiutt** [comment]
I was able to compile CMakeFile under conda environment, but when I was doing `make`, following errors occurred:
```
/usr/bin/ld: CMakeFiles/pbcvt.dir/src/python_module.cpp.o: in function `pbcvt::init_module_pbcvt()':
python_module.cpp:(.text+0x981): multiple definition of `pbcvt::init_module_pbcvt()'; CMakeFiles/pbcvt.dir/src/python_module_copy.cpp.o:python_module copy.cpp:(.text+0xe9d): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by MattLiutt** [comment]
I've solved the issues, before I close it, I would like to know what arguments should I pass into the `SparseTracker()` as I would like to use for inference on videos

**Comment by Bajrangi97** [comment]
How to solve this issue, can you explain?

**Comment by MattLiutt** [comment]
> How to solve this issue, can you explain?

I basically do a soft link and thus solve the issue.
