### ISSUE TITLE
Using other Object Detectors

### ISSUE THREAD

**Issue by calvpang** [hustvl/SparseTrack#4]
From what I understand, the model training is specifically to train an object detector with YOLOX and not training the tracker itself.
If I had a functioning YOLOv5 model, I'm assuming I could use torch.load() and run inference on each frame using that.
But I'm a bit lost on where I can do this with the current code.

**Comment by Xavier-Lin** [comment]
Thank you for your attention. We will release the inference version of YOLOV8.

**Comment by Mittag-tech** [comment]
Can I change to another detector by myself?

If the model training is to train a detector as @calvpang says, I think I can use it by setting config to a path of weghts created by training a detector separately.
Is this correct?

**Comment by Xavier-Lin** [comment]
Hi @Mittag-tech，actually, there's no problem with this. In general, you can achieve the goal of changing the detector for training by replacing the detector model in the model folder and modifying the corresponding detector <models> settings in the xxx_config.py file.

**Comment by Mittag-tech** [comment]
Thank you for your response, @Xavier-Lin .
I would try it.

Just to confirm,  is this correct that the parameters of tracking module by pseudo-depth are adjusted manually?

**Comment by Xavier-Lin** [comment]
@Mittag-tech Manually adjusting the number of layers for pseudo-depth is possible, if needed. In general, we do not adjust the number of layers for pseudo-depth, but we do adjust the matching threshold.

**Comment by Mittag-tech** [comment]
Thank you for your information, @Xavier-Lin !
