### ISSUE TITLE
Single card training

### ISSUE THREAD

**Issue by yangwhf** [hustvl/SparseTrack#5]
Hello.
Thank your for sharing the wonderful works.
Your repository has been an invaluable resource for me.
Can the model be trained using a single card? How to implement it?

**Comment by Ali96528** [comment]
Setting the option "[is_distributed = False](https://github.com/hustvl/SparseTrack/blob/4193854101d94d89ae7d89d10dea953cc90d7841/mot20_train_config.py#L12)" in train_config allows for single-card training.
Don't forget to modify batchsize and num_of_workers.
